### ISSUE TITLE
Inline Formeln

### ISSUE THREAD

**Issue by Xezarior** [zyxsachin/AccessibleEPUB#4]
Es muss ein Weg gefunden werden, Formeln inline zu erstellen, und darzustellen.

Ich befürworte den Markdown-Ansatz, da er mMn. auch für einen grafischen Formel-Editor wiederverwendet werden könnte. Dabei lehne ich mich an die Funktionsweise von Typora (https://typora.io/) an, in welchem TeX-Formeln als $$<Formel>$$ geschrieben werden.

Ich würde an dieser Stelle einfach hinterfragen, wie sehr das Editor-Fenster der "Normalen" Ansicht entsprechen muss, und ob es nötig ist, dass beide identisch sind.

**Comment by zyxsachin** [comment]
Inline Formeln wurden jetzt implementiert. Die Formeln müssen von von $$-Zeichen umgeben sein. Bsp: $$y=ax+b$$. Diese werden dann vom Editor automatisch in inline Formeln umgewandelt. Im Vorschaufenster sieht man dann wie die Formel durch MathML dargestellt wird.

Jedoch gibt es ein großes Problem. Während es im Gecko-basierten Vorschaufenster richtig dargestellt wird, können die EPUB Leseprogramme inline Formeln nicht richtig darstellen. Nur Reasily kann es in der CSS-Version richtig darstellen. Bei Calibre sind die Darstellungen uneinheitlich. Readium macht vor und nach jeder Formel Zeilenumbrüche.

**Comment by zyxsachin** [comment]
Inline formulas can be inserted in Accessible EPUB surrounded by $$-signs.

**Comment by RydrEqualsBully** [comment]
_              
     ___| |_ ___  _ __  
    / __| __/ _ \| '_ \ 
    \__ \ || (_) | |_) |
    |___/\__\___/| .__/ 
                 |_|    
                     _            _   _             
     _ __  _ __ ___ | |_ ___  ___| |_(_)_ __   __ _ 
    | '_ \| '__/ _ \| __/ _ \/ __| __| | '_ \ / _` |
    | |_) | | | (_) | ||  __/ (__| |_| | | | | (_| |
    | .__/|_|  \___/ \__\___|\___|\__|_|_| |_|\__, |
    |_|                                       |___/ 
     _           _ _ _           
    | |__  _   _| | (_) ___  ___ 
    | '_ \| | | | | | |/ _ \/ __|
    | |_) | |_| | | | |  __/\__ \
    |_.__/ \__,_|_|_|_|\___||___/
