### ISSUE TITLE
Page numbers and page breaks

### ISSUE THREAD

**Issue by zyxsachin** [zyxsachin/AccessibleEPUB#9]
Page numbers allow blind users to work better with normally sighted users, as they tend to use page numbers to go to a section of text. Page breaks should be added with a separate button or CTRL+Enter and the number of pages should increment automatically.

**Comment by zyxsachin** [comment]
Also add the changing hyperlinks right after the page number. First only do arabic numerals. Later roman numerals should be added.

**Comment by zyxsachin** [comment]
Page breaks work in both CSS and JavaScript, but the CSS ones don't always work, so that has to be investigated.

**Comment by zyxsachin** [comment]
Fixed it so it works in both JavaScript and CSS, but the reading software does not always support it.

**Comment by RydrMeansAbuse** [comment]
Stop being bullies.
